name: veiga
description: VEIGA Portfolio

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  adaptive_theme: ^3.2.1
  flutter_vector_icons: ^2.0.0
  flutter_advanced_seekbar: ^0.0.2
  spotify_sdk: ^2.3.1
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.4
  easy_splash_screen: ^1.0.4
  hoverover: ^0.1.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:

    # Environment Variables
    - assets/.env

    # Animations
    - assets/animations/
    - assets/animations/lottie/

    # Images
    - assets/images/

  # Fonts
  fonts:

    - family: SBZ

      fonts:
      
        - asset: assets/fonts/sbz.otf

    
    - family: KILO

      fonts:

        - asset: assets/fonts/kilo.otf
    